### ISSUE TITLE
chapter 8 : the type erasure design pattern code can not compile

### ISSUE THREAD

**Issue by DamonsJ** [igl42/cpp_software_design#1]
In session : An owning type erasure implemention
this code can not compile at  this line : Shape shape( drawingCircle );

Am I need to change the implemention of Shape Class ?

//---- <YourMain.cpp> ----------------

int main()
{
   // Create a circle as one representative of a concrete shape type
   Circle circle{ 3.14 };

   // Bind the circle to some drawing functionality
   auto drawingCircle = [=]() { myCircleDrawer(circle); };

   // Type-erase the circle equipped with drawing behavior
   Shape shape( drawingCircle );

   // Drawing the shape
   draw( shape );

   // ...

   return EXIT_SUCCESS;
}

**Comment by igl42** [comment]
Hi!

Thanks for providing feedback on a potential error. And you are correct: in order to make this code compile you would have to change the implementation of the `Shape` class. However, please note the formulation of the introduction sentence to this code example: "I envision a main() function that looks like this". The goal of this code example is to show a potentially "simpler" use of the `Shape` class, to show the idea of how `Shape` might work. I hope from this perspective the example makes perfect sense.

Thanks again for providing feedback,

Best regards,
   Klaus!
