### ISSUE TITLE
problems with Guideline 4.

### ISSUE THREAD

**Issue by imfineandyou0827** [igl42/cpp_software_design#6]
Hi, I have learned a lot from your book, but in guideline 4 I have two questions:1. should the “widgetDetails::BlobCollection blobs_” in wideget class be “widgetDetails::BlobCollection::blobs_” ,and if the blobs_ is a class, then does it introduce a new dependency? 2. After extracting the Blobcollection class, I rather don't quite understand how to use the widget class, and how to use the BlobCollection class to test，may you show me an example,thanks!

**Comment by igl42** [comment]
Hi!

1. No. The type of the member variable is `widgetDetails::BlobCollection` and the name of the variable is `blobs_`. The code is correct as it is. And no, it doesn't introduce a dependency, because the the `BlobCollection` is still "part" of the `Widget` class (see the name of the namespace: `widgetDetails`). However, as written in the last paragraphs of the guideline, this separation of the two aspects - `Widget` and `BlobCollection` -  fulfils the SRP, leads to better encapsulation within `Widget`, and improves testability.

2. The `Widget` class is used as before, but the extracted functionality - previously in the `private` part - is now testable separately because it is "publicly" accessible. So not `Widget` is more testable, but the `updateCollection` function and/or `BlobCollection` class.

I hope this helps,

Best regards,
   Klaus!

**Comment by imfineandyou0827** [comment]
Thanks for reply,i probably know how to test with `BlobCollection`,may i can use it like this:
```
widgetDetails::BlobCollection A;
A.updateCollection(/*some arguments*/)
```
but i still don't know how to use  `Widget`  class.`blobs_` is a private member of `Widget`,so i can't use it like this:
```
Widget B;
B.blobs_.updateCollectio(/*some arguments*/);
```
so how should i use `Widget ` class?
Thanks again!

**Comment by igl42** [comment]
Hi!

The entire guideline is about how to make the `updateCollection()` member function testable. In the end, the function becomes testable by separating it from the `Widget` class and making it publicly accessible. The guideline does not show how to use a `Widget` because this is not needed for the discussion of the `updateCollection()` member function. However, you might get an idea about how to use a `Widget` from one of the examples that shows an `addBlob()` member function:

```
class Widget
{
 public:
   // ...
   void addBlob( Blob const& blob, /*...*/ )
   {
      // ...
      updateCollection( /* ... */ );
      // ...
   }

 private:
   void updateCollection( /* some arguments needed to update the collection */ );

   std::vector<Blob> blobs_;
   /* Potentially other data members */
};

int main()
{
   Widget w;
   Blob b;
   w.addBlob( b );
   // ...
}
```

Note that calling `updateCollection()` is an entirely internal matter of the `Widget` class. Nobody else needs to call the function. But still we want it to be testable.

I hope this helps,

Best regards,
   Klaus!
